server:
  port: 8080
spring:
  application:
    name: api-gateway-server
  cloud:
    gateway:
      routes:
      - id: web-gateway
        uri: lb://web-server
        predicates:
        - Path=/**, /css/**, /images/**, /js/**, /lib/**
#        filters:
#        - RewritePath=/blog/(?<segment>.*), /$\{segment}
  #use memory or mysql
#  zipkin:
#    base-url: http://127.0.0.1:9411/
#    sender:
#      type: web
#  sleuth:
#    sampler:
#      probability: 1

  #rabbitmq
  zipkin:
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      direct:
        retry:
          enabled: true
      simple:
        retry:
          enabled: true

#eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true #use ip
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG